// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDKfgoAjBqifbKjF49QA0YsJlnqA-BwrW4",
      authDomain: "brincoboi.firebaseapp.com",
      databaseURL: "https://brincoboi-default-rtdb.firebaseio.com",
      projectId: "brincoboi",
      storageBucket: "brincoboi.appspot.com",
      messagingSenderId: "215436264786",
      appId: "1:215436264786:web:de96724267f694e021e68b");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABF6si4OJZb62N6kJlvpA39DB0sR4IgiE',
    appId: '1:215436264786:android:fd438e0c0d02773f21e68b',
    messagingSenderId: '215436264786',
    projectId: 'brincoboi',
    databaseURL: 'https://brincoboi-default-rtdb.firebaseio.com/',
    storageBucket: 'brincoboi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Zyz1AHvWl-jKmHuEgLSgbvof4IRShqc',
    appId: '1:215436264786:ios:855079f81eb31b3f21e68b',
    messagingSenderId: '215436264786',
    projectId: 'brincoboi',
    storageBucket: 'brincoboi.appspot.com',
    iosClientId:
        '215436264786-pgpston0qpaq5uni08tp8vge8opklgeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.brincoDeBoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Zyz1AHvWl-jKmHuEgLSgbvof4IRShqc',
    appId: '1:215436264786:ios:855079f81eb31b3f21e68b',
    messagingSenderId: '215436264786',
    projectId: 'brincoboi',
    storageBucket: 'brincoboi.appspot.com',
    iosClientId:
        '215436264786-pgpston0qpaq5uni08tp8vge8opklgeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.brincoDeBoi',
  );
}
