// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGfGcRMEReW68kkHeFrrrkd_zDvctC8Wo',
    appId: '1:326184110814:web:d02b745e822330f462d04f',
    messagingSenderId: '326184110814',
    projectId: 'melocaliza-bbed3',
    authDomain: 'melocaliza-bbed3.firebaseapp.com',
    databaseURL: 'https://melocaliza-bbed3-default-rtdb.firebaseio.com',
    storageBucket: 'melocaliza-bbed3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeg4J5rAS1StYj6qFZ8eSWpTfvvwwGZ8k',
    appId: '1:326184110814:android:f2c773177c4af8c062d04f',
    messagingSenderId: '326184110814',
    projectId: 'melocaliza-bbed3',
    databaseURL: 'https://melocaliza-bbed3-default-rtdb.firebaseio.com',
    storageBucket: 'melocaliza-bbed3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRuhD0QzXI8slIzVS3QPxvBoxczV_BfE',
    appId: '1:326184110814:ios:de7e7e075173ae6f62d04f',
    messagingSenderId: '326184110814',
    projectId: 'melocaliza-bbed3',
    databaseURL: 'https://melocaliza-bbed3-default-rtdb.firebaseio.com',
    storageBucket: 'melocaliza-bbed3.appspot.com',
    iosClientId: '326184110814-kvlf2lb6r6k2sire2op8b09q9rh4giqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.brincoDeBoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRuhD0QzXI8slIzVS3QPxvBoxczV_BfE',
    appId: '1:326184110814:ios:de7e7e075173ae6f62d04f',
    messagingSenderId: '326184110814',
    projectId: 'melocaliza-bbed3',
    databaseURL: 'https://melocaliza-bbed3-default-rtdb.firebaseio.com',
    storageBucket: 'melocaliza-bbed3.appspot.com',
    iosClientId: '326184110814-kvlf2lb6r6k2sire2op8b09q9rh4giqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.brincoDeBoi',
  );
}
