// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoi3DTWmVLpAGwTSdHkCD22TreEK8spjs',
    appId: '1:271329829117:web:77a00f56ca8d31db115e94',
    messagingSenderId: '271329829117',
    projectId: 'sysvia-115d8',
    authDomain: 'sysvia-115d8.firebaseapp.com',
    databaseURL: 'https://sysvia-115d8-default-rtdb.firebaseio.com',
    storageBucket: 'sysvia-115d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhER_HhSj7imc7Nw8vrIZLzM9USrNeTRU',
    appId: '1:271329829117:android:88598c61f9d3feb7115e94',
    messagingSenderId: '271329829117',
    projectId: 'sysvia-115d8',
    databaseURL: 'https://sysvia-115d8-default-rtdb.firebaseio.com',
    storageBucket: 'sysvia-115d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUDjEuM93kzpVDt02nH8ilX13sftgG-Ls',
    appId: '1:271329829117:ios:a095a1c7f2d56a78115e94',
    messagingSenderId: '271329829117',
    projectId: 'sysvia-115d8',
    databaseURL: 'https://sysvia-115d8-default-rtdb.firebaseio.com',
    storageBucket: 'sysvia-115d8.appspot.com',
    iosClientId: '271329829117-spreoerarn3q4mrnh0v27ks96vntkt6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sysviaDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUDjEuM93kzpVDt02nH8ilX13sftgG-Ls',
    appId: '1:271329829117:ios:a095a1c7f2d56a78115e94',
    messagingSenderId: '271329829117',
    projectId: 'sysvia-115d8',
    databaseURL: 'https://sysvia-115d8-default-rtdb.firebaseio.com',
    storageBucket: 'sysvia-115d8.appspot.com',
    iosClientId: '271329829117-spreoerarn3q4mrnh0v27ks96vntkt6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sysviaDash',
  );
}
